// RC2.8-2. The blueprint catalogue: the SEMANTIC space the scheduler chooses
// from, before a single number, name or sentence is drawn.
//
// The defect this exists to fix.
//
// Generation used to run one way round: draw a question, look at what came out,
// and reject it if it repeated something. On a 100-question sitting that took
// 621 candidates to publish 100 — 521 rejections — and the repetition still got
// through, because a rejection-driven loop has no idea what it is LOOKING for.
// It cannot aim at the thing the session is short of; it can only refuse what it
// happens to be handed, and when the retry budget runs out it takes whatever is
// left. That is why the repetition concentrated in the last third of a session.
//
// So the order is inverted. A blueprint — family, band, template, the task it
// asks, the way it lays its information out — is chosen FIRST, against what the
// session already contains, and the renderer is then told which blueprint to
// realise. Numbers, names, scenario and wording are drawn afterwards and cannot
// change the blueprint.
//
// GENERATED FILE. Rebuild with:
//     node tools/audit/rc28-build-blueprints.mjs
// tests/rc28-blueprints.test.mjs re-derives it against the live engine on every
// run, so a template that changes which tasks it asks, or that stops being
// reachable at its band, fails the test rather than silently leaving the
// scheduler planning against a fiction.
//
// `targets` lists the unknowns a template was observed to ask for that task.
// `signatures` lists the perceptual identities it was observed to realise, and
// IS an input to selection: an idea whose signature this user has already met is
// not offered again while the band holds one they have not.

/**
 * @typedef {object} Blueprint
 * @property {string} templateId  which template realises it
 * @property {string} family
 * @property {'easy'|'medium'|'hard'} band
 * @property {string} task        the normalised job and answer class
 * @property {string} info        how the information is laid out
 * @property {string[]} targets   the unknowns observed for this task
 * @property {string[]} signatures the perceptual identities it was observed to realise
 */

/** @type {Blueprint[]} */
export const BLUEPRINTS = Object.freeze([
  {templateId: 'AGE_E_MULT_DIFF', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'PRESENT_RATIO_AND_DIFFERENCE', targets: ['youngerAge'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(#,sub(mul(#,X),X))|path:subtract>divide|info:PRESENT_RATIO_AND_DIFFERENCE|entry:forward']},
  {templateId: 'AGE_E_SUM_DIFF', family: 'ages', band: 'easy', task: 'DECOMPOSE_COMBINED/AGE', info: 'PRESENT_SUM_AND_DIFFERENCE', targets: ['olderAge'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(#,add(X,sub(X,#)))|path:divide>ratio>add|info:PRESENT_SUM_AND_DIFFERENCE|entry:forward']},
  {templateId: 'AGE_H_PAST_FUT', family: 'ages', band: 'hard', task: 'DECOMPOSE_COMBINED/AGE', info: 'PAST_AND_FUTURE_CONDITIONS', targets: ['olderAgeNow'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(mul(#,sub(sub(sub(#,mul(#,#)),X),#)),sub(X,#))|path:multiply>subtract>add>divide|info:PAST_AND_FUTURE_CONDITIONS|entry:forward']},
  {templateId: 'AGE_H_THREE_SIBLINGS', family: 'ages', band: 'medium', task: 'FORWARD_COMPUTE/AGE', info: 'THREE_PERSON_SYSTEM', targets: ['eldestAfterYears'], signatures: ['task:FORWARD_COMPUTE|qty:AGE|rel:eq(#,sub(mul(#,sub(X,#)),#))|path:add>multiply>subtract>divide|info:THREE_PERSON_SYSTEM|entry:forward']},
  {templateId: 'AGE_H_TWO_TIME', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'RELATION_AT_TWO_TIMES', targets: ['youngerAgeNow'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(add(#,#,X),mul(#,add(#,X)))|path:add>ratio>multiply>subtract>divide|info:RELATION_AT_TWO_TIMES|entry:forward']},
  {templateId: 'AGE_M_DIFFERENCE_INVARIANT', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'TWO_RATIOS_ASK_INVARIANT', targets: ['ageDifference'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(mul(#,sub(#,#)),mul(X,sub(#,#)))|path:add>multiply>ratio>subtract>divide|info:TWO_RATIOS_ASK_INVARIANT|entry:comparison']},
  {templateId: 'AGE_M_FUT_RATIO', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'PRESENT_DIFFERENCE_FUTURE_RATIO', targets: ['youngerAgeNow'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(add(#,#,X),mul(#,add(#,X)))|path:add>ratio>multiply>subtract>divide|info:PRESENT_DIFFERENCE_FUTURE_RATIO|entry:forward']},
  {templateId: 'AGE_M_FUT_SUM_DIFF', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'PRESENT_DIFFERENCE_FUTURE_SUM', targets: ['olderAgeNow'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(#,add(add(#,X),add(#,sub(X,#))))|path:multiply>subtract>divide>add|info:PRESENT_DIFFERENCE_FUTURE_SUM|entry:forward']},
  {templateId: 'AGE_M_PAST_RATIO', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'PAST_RELATION_ASK_PRESENT', targets: ['olderAgeNow'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(mul(#,sub(sub(X,#),#)),sub(X,#))|path:subtract>multiply>divide>add>ratio|info:PAST_RELATION_ASK_PRESENT|entry:reverse']},
  {templateId: 'AGE_M_RATIO_FUT_SUM', family: 'ages', band: 'medium', task: 'DECOMPOSE_COMBINED/AGE', info: 'PRESENT_RATIO_FUTURE_SUM', targets: ['olderAgeNow'], signatures: ['task:DECOMPOSE_COMBINED|qty:AGE|rel:eq(add(X,mul(#,#,#),mul(#,X)),mul(#,#))|path:multiply>subtract>add>divide|info:PRESENT_RATIO_FUTURE_SUM|entry:forward']},
  {templateId: 'AGE_M_WHEN_RATIO', family: 'ages', band: 'medium', task: 'REQUIRED_INPUT/DURATION', info: 'PRESENT_AGES_ASK_ELAPSED', targets: ['yearsUntilRatio'], signatures: ['task:REQUIRED_INPUT|qty:DURATION|rel:eq(add(#,X),mul(#,add(#,X)))|path:add>multiply>ratio>subtract>divide|info:PRESENT_AGES_ASK_ELAPSED|entry:reverse']},
  {templateId: 'AVG_E_ADD', family: 'averages', band: 'easy', task: 'FORWARD_COMPUTE/AVERAGE', info: 'BEFORE_AFTER_CHANGE', targets: ['newAverageAfterAdd'], signatures: ['task:FORWARD_COMPUTE|qty:AVERAGE|rel:eq(add(#,mul(#,#)),mul(#,X))|path:multiply>add>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'AVG_E_REMOVE', family: 'averages', band: 'easy', task: 'FORWARD_COMPUTE/AVERAGE', info: 'BEFORE_AFTER_CHANGE', targets: ['newAverageAfterRemove'], signatures: ['task:FORWARD_COMPUTE|qty:AVERAGE|rel:eq(mul(#,X),sub(mul(#,#),#))|path:multiply>subtract>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'AVG_H_COMB_ADD', family: 'averages', band: 'medium', task: 'COMBINE_PARTS/AVERAGE', info: 'PARTITION_OF_WHOLE', targets: ['weightedAveragePlusValue'], signatures: ['task:COMBINE_PARTS|qty:AVERAGE|rel:eq(add(#,mul(#,#),mul(#,#)),mul(#,X))|path:multiply>add>divide|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'AVG_H_OVERLAP', family: 'averages', band: 'hard', task: 'DECOMPOSE_COMBINED/MEMBER_VALUE', info: 'OVERLAPPING_GROUPS', targets: ['overlappingValue'], signatures: ['task:DECOMPOSE_COMBINED|qty:MEMBER_VALUE|rel:eq(add(X,mul(#,#)),add(mul(#,#),mul(#,#)))|path:multiply>add>ratio>subtract|info:OVERLAPPING_GROUPS|entry:forward']},
  {templateId: 'AVG_H_SPLIT_SIZE', family: 'averages', band: 'medium', task: 'DECOMPOSE_COMBINED/COUNT', info: 'PARTITION_OF_WHOLE', targets: ['firstGroupCount'], signatures: ['task:DECOMPOSE_COMBINED|qty:COUNT|rel:eq(add(mul(#,X),mul(#,sub(#,X))),mul(#,#))|path:multiply>subtract>divide|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'AVG_H_TARGET', family: 'averages', band: 'medium', task: 'REQUIRED_INPUT/MEMBER_VALUE', info: 'BEFORE_AFTER_CHANGE', targets: ['valueForTargetAverage'], signatures: ['task:REQUIRED_INPUT|qty:MEMBER_VALUE|rel:eq(add(X,mul(#,#)),mul(#,#))|path:multiply>subtract|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'AVG_M_ADD_PAIR', family: 'averages', band: 'medium', task: 'FORWARD_COMPUTE/AVERAGE', info: 'BEFORE_AFTER_CHANGE', targets: ['averageAfterAddingPair'], signatures: ['task:FORWARD_COMPUTE|qty:AVERAGE|rel:eq(add(mul(#,#),mul(#,#)),mul(#,X))|path:multiply>add>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'AVG_M_COMBINE', family: 'averages', band: 'medium', task: 'COMBINE_PARTS/AVERAGE', info: 'PARTITION_OF_WHOLE', targets: ['weightedAverage'], signatures: ['task:COMBINE_PARTS|qty:AVERAGE|rel:eq(add(mul(#,#),mul(#,#)),mul(#,X))|path:multiply>add>divide|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'AVG_M_REPLACE', family: 'averages', band: 'medium', task: 'FORWARD_COMPUTE/AVERAGE', info: 'BEFORE_AFTER_CHANGE', targets: ['newAverageAfterReplace'], signatures: ['task:FORWARD_COMPUTE|qty:AVERAGE|rel:eq(add(#,sub(mul(#,#),#)),mul(#,X))|path:multiply>subtract>add>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'CAL_E_AFTER', family: 'calendar', band: 'easy', task: 'REVERSE_RECOVER/DATE', info: 'CALENDAR_OFFSET', targets: ['todayFromOffset'], signatures: ['task:REVERSE_RECOVER|qty:DATE|rel:eq(#,mod(add(#,X),#))|path:none|info:CALENDAR_OFFSET|entry:forward']},
  {templateId: 'CAL_E_TOM', family: 'calendar', band: 'easy', task: 'REVERSE_RECOVER/DATE', info: 'CALENDAR_OFFSET', targets: ['todayFromOffset'], signatures: ['task:REVERSE_RECOVER|qty:DATE|rel:eq(#,mod(add(#,X),#))|path:none|info:CALENDAR_OFFSET|entry:forward']},
  {templateId: 'CAL_H_CYCLE_MEET', family: 'calendar', band: 'medium', task: 'FIND_COINCIDENCE/DATE', info: 'TWO_CYCLES', targets: ['meetingWeekday'], signatures: ['task:FIND_COINCIDENCE|qty:DATE|rel:eq(X,mod(add(#,#),#))|path:multiply>subtract>ratio|info:TWO_CYCLES|entry:forward']},
  {templateId: 'CAL_H_LONG', family: 'calendar', band: 'easy', task: 'FORWARD_COMPUTE/DATE', info: 'CALENDAR_OFFSET', targets: ['dayAfterLongOffset'], signatures: ['task:FORWARD_COMPUTE|qty:DATE|rel:eq(X,mod(add(#,#),#))|path:subtract>ratio|info:CALENDAR_OFFSET|entry:forward']},
  {templateId: 'CAL_H_MONTH_LENGTH', family: 'calendar', band: 'hard', task: 'MEASURE_INTERVAL/DURATION', info: 'TWO_ENDPOINTS', targets: ['daysBetweenDates'], signatures: ['task:MEASURE_INTERVAL|qty:DURATION|rel:eq(#,mod(add(#,X),#))|path:add>subtract|info:TWO_ENDPOINTS|entry:reverse']},
  {templateId: 'CAL_H_NESTED', family: 'calendar', band: 'easy', task: 'REVERSE_RECOVER/DATE', info: 'CALENDAR_OFFSET', targets: ['todayFromNestedOffset'], signatures: ['task:REVERSE_RECOVER|qty:DATE|rel:eq(#,mod(add(#,X),#))|path:add>subtract>ratio|info:CALENDAR_OFFSET|entry:forward']},
  {templateId: 'CAL_H_OFFSET_CYCLES', family: 'calendar', band: 'hard', task: 'FIND_COINCIDENCE/DATE', info: 'TWO_CYCLES', targets: ['firstSharedWeekday'], signatures: ['task:FIND_COINCIDENCE|qty:DATE|rel:eq(X,mod(add(#,#),#))|path:multiply>subtract>ratio|info:TWO_CYCLES|entry:forward']},
  {templateId: 'CAL_M_COMPOUND', family: 'calendar', band: 'easy', task: 'REVERSE_RECOVER/DATE', info: 'CALENDAR_OFFSET', targets: ['todayFromCompoundOffset'], signatures: ['task:REVERSE_RECOVER|qty:DATE|rel:eq(#,mod(add(#,X),#))|path:add|info:CALENDAR_OFFSET|entry:forward']},
  {templateId: 'CAL_M_TWO_SHIFT', family: 'calendar', band: 'easy', task: 'REVERSE_RECOVER/DATE', info: 'CALENDAR_OFFSET', targets: ['pastDayFromFutureAnchor'], signatures: ['task:REVERSE_RECOVER|qty:DATE|rel:eq(#,mod(add(#,X),#))|path:ratio>add|info:CALENDAR_OFFSET|entry:forward']},
  {templateId: 'COMB_E_OUTPUT', family: 'combined_rate', band: 'easy', task: 'COMBINE_PARTS/QUANTITY', info: 'DIRECT_GIVENS', targets: ['jointOutput'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(X,add(mul(#,#),mul(#,#)))|path:add>multiply|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'COMB_E_THREE', family: 'combined_rate', band: 'easy', task: 'COMBINE_PARTS/QUANTITY', info: 'DIRECT_GIVENS', targets: ['jointOutput'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(X,add(mul(#,#),mul(#,#),mul(#,#)))|path:add>multiply|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'COMB_E_TIME', family: 'combined_rate', band: 'easy', task: 'COMBINE_PARTS/DURATION', info: 'DIRECT_GIVENS', targets: ['jointTime'], signatures: ['task:COMBINE_PARTS|qty:DURATION|rel:eq(#,add(mul(#,X),mul(#,X)))|path:add>divide|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'COMB_H_STAGED', family: 'combined_rate', band: 'medium', task: 'DECOMPOSE_COMBINED/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['finalSoloTime'], signatures: ['task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(#,add(mul(#,#),mul(#,X),mul(#,add(#,#))))|path:multiply>add>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'COMB_H_TEAM_SIZE', family: 'combined_rate', band: 'medium', task: 'DECOMPOSE_COMBINED/COUNT', info: 'CONSTRAINT_SET', targets: ['initialTeamSize'], signatures: ['task:DECOMPOSE_COMBINED|qty:COUNT|rel:eq(#,add(mul(#,#,X),mul(#,#,add(#,X))))|path:multiply>add>subtract>divide|info:CONSTRAINT_SET|entry:forward']},
  {templateId: 'COMB_H_TWO_PUMPS', family: 'combined_rate', band: 'hard', task: 'DECOMPOSE_COMBINED/DURATION', info: 'CONSTRAINT_SET', targets: ['firstPumpSoloHours', 'secondPumpSoloHours'], signatures: ['task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(mul(#,#),mul(X,sub(#,#)))|path:divide>subtract>ratio>multiply|info:CONSTRAINT_SET|entry:forward', 'task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(mul(#,sub(#,#)),mul(X,sub(#,#)))|path:divide>subtract>ratio>multiply|info:CONSTRAINT_SET|entry:forward']},
  {templateId: 'COMB_M_SOLO_THEN', family: 'combined_rate', band: 'medium', task: 'COMBINE_PARTS/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['jointTimeAfterSolo'], signatures: ['task:COMBINE_PARTS|qty:DURATION|rel:eq(#,add(mul(#,#),mul(X,add(#,#))))|path:multiply>subtract>add>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'COMB_M_TOGETHER_SOLO', family: 'combined_rate', band: 'medium', task: 'DECOMPOSE_COMBINED/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['soloTimeAfterJoint'], signatures: ['task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(#,add(mul(#,X),mul(#,add(#,#))))|path:multiply>add>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PROP_E_COST', family: 'direct_proportion', band: 'easy', task: 'REQUIRED_INPUT/QUANTITY', info: 'DIRECT_GIVENS', targets: ['requiredInput'], signatures: ['task:REQUIRED_INPUT|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PROP_E_COST', family: 'direct_proportion', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PROP_E_ITEMS', family: 'direct_proportion', band: 'easy', task: 'REQUIRED_INPUT/QUANTITY', info: 'DIRECT_GIVENS', targets: ['requiredInput'], signatures: ['task:REQUIRED_INPUT|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PROP_E_ITEMS', family: 'direct_proportion', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PROP_H_BREAK_EVEN', family: 'direct_proportion', band: 'hard', task: 'FIND_THRESHOLD/QUANTITY', info: 'TWO_CONFIGURATIONS', targets: ['smallestQuantityWhereSecondPlanWins'], signatures: ['task:FIND_THRESHOLD|qty:QUANTITY|rel:eq(#,mul(#,sub(X,#)))|path:subtract>multiply>divide>add>ratio|info:TWO_CONFIGURATIONS|entry:comparison']},
  {templateId: 'PROP_H_CAPITAL_TIME', family: 'direct_proportion', band: 'hard', task: 'SHARE_PROPORTIONALLY/MONEY', info: 'PARTITION_OF_WHOLE', targets: ['firstPartnerShare', 'secondPartnerShare'], signatures: ['task:SHARE_PROPORTIONALLY|qty:MONEY|rel:eq(mul(#,mul(#,#)),mul(X,add(mul(#,#),mul(#,#))))|path:multiply>add>divide|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'PROP_H_COMPOUND', family: 'direct_proportion', band: 'medium', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'MULTI_STAGE_PROCESS', targets: ['scaledOutputPlusReserve'], signatures: ['task:SCALE_PROPORTIONALLY|qty:QUANTITY|rel:eq(mul(#,#,add(#,#)),mul(X,mul(#,#)))|path:divide>multiply>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PROP_H_COST_PLUS', family: 'direct_proportion', band: 'easy', task: 'SCALE_PROPORTIONALLY/MONEY', info: 'DIRECT_GIVENS', targets: ['scaledOutputPlusFee'], signatures: ['task:SCALE_PROPORTIONALLY|qty:MONEY|rel:eq(mul(#,#),mul(#,sub(X,#)))|path:divide>multiply>add>ratio|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'PROP_H_REPLACE', family: 'direct_proportion', band: 'hard', task: 'REVERSE_RECOVER/VOLUME', info: 'BEFORE_AFTER_CHANGE', targets: ['replacedVolume'], signatures: ['task:REVERSE_RECOVER|qty:VOLUME|rel:eq(mul(#,X),mul(#,sub(#,#)))|path:add>multiply>divide>subtract|info:BEFORE_AFTER_CHANGE|entry:reverse']},
  {templateId: 'PROP_H_TWO_ITEM_SYSTEM', family: 'direct_proportion', band: 'medium', task: 'DECOMPOSE_COMBINED/MONEY', info: 'CONSTRAINT_SET', targets: ['boxUnitPrice'], signatures: ['task:DECOMPOSE_COMBINED|arch:TWO_EQUATION_SYSTEM|entry:forward']},
  {templateId: 'PROP_M_FRAC_UNIT', family: 'direct_proportion', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PROP_M_MAP', family: 'direct_proportion', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput'], signatures: ['task:SCALE_PROPORTIONALLY|qty:QUANTITY|rel:eq(mul(#,X),mul(#,add(#,#)))|path:add>divide>multiply|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'PROP_M_RECIPE', family: 'direct_proportion', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput', 'scaledOutputFromResource'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'FRAC_E_2', family: 'fractions', band: 'easy', task: 'FORWARD_COMPUTE/NUMBER', info: 'MULTI_STAGE_PROCESS', targets: ['chainResult'], signatures: ['task:FORWARD_COMPUTE|qty:NUMBER|rel:eq(#,mul(#,X))|path:divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'FRAC_E_2', family: 'fractions', band: 'easy', task: 'REVERSE_RECOVER/NUMBER', info: 'MULTI_STAGE_PROCESS', targets: ['startNumber'], signatures: ['task:REVERSE_RECOVER|qty:NUMBER|rel:eq(X,mul(#,#))|path:multiply>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'FRAC_H_4', family: 'fractions', band: 'easy', task: 'FORWARD_COMPUTE/NUMBER', info: 'MULTI_STAGE_PROCESS', targets: ['chainResult'], signatures: ['task:FORWARD_COMPUTE|qty:NUMBER|rel:eq(#,mul(#,X))|path:divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'FRAC_H_4', family: 'fractions', band: 'easy', task: 'REVERSE_RECOVER/NUMBER', info: 'MULTI_STAGE_PROCESS', targets: ['hiddenFraction', 'startNumber'], signatures: ['task:REVERSE_RECOVER|qty:NUMBER|rel:eq(#,mul(X,mul(#,#)))|path:multiply>divide|info:MULTI_STAGE_PROCESS|entry:forward', 'task:REVERSE_RECOVER|qty:NUMBER|rel:eq(X,mul(#,#))|path:multiply>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'FRAC_M_3', family: 'fractions', band: 'easy', task: 'FORWARD_COMPUTE/NUMBER', info: 'MULTI_STAGE_PROCESS', targets: ['chainResult'], signatures: ['task:FORWARD_COMPUTE|qty:NUMBER|rel:eq(#,mul(#,X))|path:divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'FRAC_M_3', family: 'fractions', band: 'easy', task: 'REVERSE_RECOVER/NUMBER', info: 'MULTI_STAGE_PROCESS', targets: ['hiddenFraction', 'startNumber'], signatures: ['task:REVERSE_RECOVER|qty:NUMBER|rel:eq(#,mul(X,mul(#,#)))|path:multiply>divide|info:MULTI_STAGE_PROCESS|entry:forward', 'task:REVERSE_RECOVER|qty:NUMBER|rel:eq(X,mul(#,#))|path:multiply>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'FRAC_M_REMAIN', family: 'fractions', band: 'medium', task: 'FIND_REMAINDER/NUMBER', info: 'PARTITION_OF_WHOLE', targets: ['remainingFraction'], signatures: ['task:FIND_REMAINDER|qty:NUMBER|rel:eq(X,mul(sub(#,#),sub(#,#)))|path:divide>subtract>multiply|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'MACH_E_HOURS', family: 'machines', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'TWO_CONFIGURATIONS', targets: ['outputForNewSetup'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'MACH_E_REQUIRED', family: 'machines', band: 'medium', task: 'REQUIRED_INPUT/COUNT', info: 'DIRECT_GIVENS', targets: ['machinesForTarget'], signatures: ['task:REQUIRED_INPUT|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'MACH_H_MIN_SECOND_TYPE', family: 'machines', band: 'hard', task: 'FIND_THRESHOLD/COUNT', info: 'CONSTRAINT_SET', targets: ['minimumSecondTypeMachines'], signatures: ['task:FIND_THRESHOLD|qty:COUNT|rel:gt(#,add(#,mul(#,sub(X,#)))) & gte(add(#,mul(#,X)),#) & int(X,#)|path:multiply>subtract>divide>add>ratio|info:CONSTRAINT_SET|entry:minimum']},
  {templateId: 'MACH_H_STAGE_UP', family: 'machines', band: 'medium', task: 'COMBINE_PARTS/QUANTITY', info: 'MULTI_STAGE_PROCESS', targets: ['totalAcrossStages'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(add(mul(#,#,#,#),mul(#,add(mul(#,#,#),mul(#,#,add(#,#))))),mul(#,X))|path:multiply>divide>add>subtract|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'MACH_H_STOPPAGE_TIME', family: 'machines', band: 'medium', task: 'REVERSE_RECOVER/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['stoppageHour'], signatures: ['task:REVERSE_RECOVER|qty:DURATION|rel:eq(#,sub(mul(#,#,#),mul(#,sub(#,X))))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'MACH_H_TWO_CONFIG', family: 'machines', band: 'medium', task: 'DECOMPOSE_COMBINED/RATE', info: 'TWO_CONFIGURATIONS', targets: ['firstTypeRate'], signatures: ['task:DECOMPOSE_COMBINED|arch:TWO_EQUATION_SYSTEM|entry:forward']},
  {templateId: 'MACH_H_TWO_TYPES', family: 'machines', band: 'medium', task: 'COMBINE_PARTS/QUANTITY', info: 'TWO_CONFIGURATIONS', targets: ['mixedFleetOutput'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(X,add(mul(#,#,#),mul(#,#,#)))|path:multiply>add|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'MACH_M_NEW_FAST', family: 'machines', band: 'medium', task: 'COMBINE_PARTS/QUANTITY', info: 'TWO_CONFIGURATIONS', targets: ['mixedPairOutput'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(mul(#,#,#,X),mul(#,#,add(#,#)))|path:multiply>divide>add|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'MACH_M_STOP', family: 'machines', band: 'medium', task: 'COMBINE_PARTS/QUANTITY', info: 'MULTI_STAGE_PROCESS', targets: ['totalAcrossStages'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(X,add(mul(#,#,#),mul(#,#,#)))|path:multiply>subtract>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'MACH_M_SUBSET_UP', family: 'machines', band: 'medium', task: 'COMBINE_PARTS/QUANTITY', info: 'TWO_CONFIGURATIONS', targets: ['mixedGroupOutput'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(mul(#,X),mul(#,add(mul(#,#,#),mul(#,#,add(#,#)))))|path:divide>add>multiply>subtract|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'ODD_E_MULT', family: 'odd_one_out', band: 'easy', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:MULTIPLE|path:multiply|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_E_SQUARES', family: 'odd_one_out', band: 'easy', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:SQUARE|path:multiply|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_H_SQ_MINUS', family: 'odd_one_out', band: 'medium', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:SQUARE_MINUS_ONE|path:multiply>add|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_H_TRIANGULAR', family: 'odd_one_out', band: 'medium', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:TRIANGULAR|path:multiply>divide|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_M_CUBES', family: 'odd_one_out', band: 'easy', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:CUBE|path:multiply|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_M_EXTEND', family: 'odd_one_out', band: 'medium', task: 'EXTEND_BY_PROPERTY/NUMBER', info: 'SET_EXTENSION', targets: ['setMember'], signatures: ['task:EXTEND_BY_PROPERTY|qty:NUMBER|rel:none|path:none|info:SET_EXTENSION|entry:forward']},
  {templateId: 'ODD_M_PRIME2', family: 'odd_one_out', band: 'easy', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:PRIME_DOUBLE|path:divide|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_M_PRONIC', family: 'odd_one_out', band: 'easy', task: 'IDENTIFY_MEMBER/NUMBER', info: 'SET_DISPLAY', targets: ['outlier'], signatures: ['task:IDENTIFY_MEMBER|qty:NUMBER|rel:ruleset:PRONIC|path:multiply|info:SET_DISPLAY|entry:forward']},
  {templateId: 'ODD_M_PROPERTY', family: 'odd_one_out', band: 'medium', task: 'IDENTIFY_RULE/RULE', info: 'RULE_CHOICE', targets: ['sharedProperty'], signatures: ['task:IDENTIFY_RULE|qty:RULE|rel:none|path:ratio|info:RULE_CHOICE|entry:forward']},
  {templateId: 'PCT_E_OF', family: 'percentages', band: 'easy', task: 'FORWARD_COMPUTE/QUANTITY', info: 'DIRECT_GIVENS', targets: ['percentOfValue'], signatures: ['task:FORWARD_COMPUTE|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PCT_E_REVERSE_ONE', family: 'percentages', band: 'medium', task: 'REVERSE_RECOVER/MONEY', info: 'BEFORE_AFTER_CHANGE', targets: ['originalFromFinal'], signatures: ['task:REVERSE_RECOVER|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PCT_H_CHAIN_VALUE', family: 'percentages', band: 'medium', task: 'APPLY_SUCCESSIVE_CHANGE/MONEY', info: 'MULTI_STAGE_PROCESS', targets: ['finalAfterTwoChanges'], signatures: ['task:APPLY_SUCCESSIVE_CHANGE|qty:MONEY|rel:eq(mul(#,X),mul(#,add(#,#),sub(#,#)))|path:multiply>divide>subtract>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PCT_H_MIXTURE', family: 'percentages', band: 'medium', task: 'DECOMPOSE_COMBINED/VOLUME', info: 'PARTITION_OF_WHOLE', targets: ['firstComponentVolume'], signatures: ['task:DECOMPOSE_COMBINED|qty:VOLUME|rel:eq(add(mul(#,X),mul(#,sub(#,X))),mul(#,#))|path:multiply>divide>percent>subtract|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'PCT_H_REVERSE_CHAIN', family: 'percentages', band: 'medium', task: 'REVERSE_RECOVER/MONEY', info: 'MULTI_STAGE_PROCESS', targets: ['originalFromTwoChanges'], signatures: ['task:REVERSE_RECOVER|qty:MONEY|rel:eq(mul(#,#),mul(X,add(#,#),sub(#,#)))|path:divide>add>subtract>multiply|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PCT_H_TWO_GROUP_CHANGE', family: 'percentages', band: 'hard', task: 'DECOMPOSE_COMBINED/COUNT', info: 'CONSTRAINT_SET', targets: ['firstGroupSize', 'secondGroupSize'], signatures: ['task:DECOMPOSE_COMBINED|qty:COUNT|rel:eq(add(mul(#,X),mul(#,sub(#,X))),mul(#,#))|path:multiply>divide>subtract>percent>add>ratio|info:CONSTRAINT_SET|entry:forward', 'task:DECOMPOSE_COMBINED|qty:COUNT|rel:eq(add(mul(#,X),mul(#,sub(#,X))),mul(#,#))|path:multiply>divide>subtract>percent>add|info:CONSTRAINT_SET|entry:forward']},
  {templateId: 'PCT_M_REMAIN', family: 'percentages', band: 'easy', task: 'APPLY_SUCCESSIVE_CHANGE/QUANTITY', info: 'MULTI_STAGE_PROCESS', targets: ['remainingAfterTwoStages'], signatures: ['task:APPLY_SUCCESSIVE_CHANGE|qty:QUANTITY|rel:eq(mul(#,X),mul(#,sub(#,#),sub(#,#)))|path:multiply>divide>subtract|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PCT_M_SUCCESSIVE', family: 'percentages', band: 'medium', task: 'MEASURE_CHANGE/PERCENT', info: 'MULTI_STAGE_PROCESS', targets: ['netPercentChange'], signatures: ['task:MEASURE_CHANGE|qty:PERCENT|rel:eq(mul(#,X),sub(mul(#,#),#))|path:multiply>divide>add>subtract|info:MULTI_STAGE_PROCESS|entry:forward', 'task:MEASURE_CHANGE|qty:PERCENT|rel:eq(mul(#,X),sub(mul(#,#),#))|path:multiply>divide>subtract>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PCT_M_UNIT_PRICE', family: 'percentages', band: 'easy', task: 'SCALE_PROPORTIONALLY/MONEY', info: 'BEFORE_AFTER_CHANGE', targets: ['scaledCostAfterIncrease'], signatures: ['task:SCALE_PROPORTIONALLY|qty:MONEY|rel:eq(mul(#,#,X),mul(#,#,add(#,#)))|path:divide>add>multiply|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'PL_E_LOSS', family: 'profit_loss', band: 'easy', task: 'MEASURE_CHANGE/PERCENT', info: 'DIRECT_GIVENS', targets: ['lossPercent'], signatures: ['task:MEASURE_CHANGE|qty:PERCENT|rel:eq(mul(#,X),mul(#,sub(#,#)))|path:subtract>multiply>divide|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'PL_E_PROFIT', family: 'profit_loss', band: 'easy', task: 'MEASURE_CHANGE/PERCENT', info: 'DIRECT_GIVENS', targets: ['profitPercent'], signatures: ['task:MEASURE_CHANGE|qty:PERCENT|rel:eq(mul(#,X),mul(#,sub(#,#)))|path:subtract>multiply>divide|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'PL_H_CHAIN', family: 'profit_loss', band: 'medium', task: 'MEASURE_CHANGE/PERCENT', info: 'MULTI_STAGE_PROCESS', targets: ['netPercentChange'], signatures: ['task:MEASURE_CHANGE|qty:PERCENT|rel:eq(mul(#,X),sub(mul(#,#),#))|path:multiply>divide>subtract>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PL_H_MARKUP_DISCOUNT', family: 'profit_loss', band: 'medium', task: 'REVERSE_RECOVER/MONEY', info: 'MULTI_STAGE_PROCESS', targets: ['costFromNetFactor'], signatures: ['task:REVERSE_RECOVER|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PL_H_REST_MARGIN', family: 'profit_loss', band: 'hard', task: 'REVERSE_RECOVER/PERCENT', info: 'PARTITION_OF_WHOLE', targets: ['remainderMarginPercent'], signatures: ['task:REVERSE_RECOVER|qty:PERCENT|rel:eq(add(mul(#,#),mul(#,X)),mul(#,#))|path:subtract>multiply>divide|info:PARTITION_OF_WHOLE|entry:reverse']},
  {templateId: 'PL_H_REVERSE', family: 'profit_loss', band: 'easy', task: 'REVERSE_RECOVER/MONEY', info: 'BEFORE_AFTER_CHANGE', targets: ['costFromSellPrice'], signatures: ['task:REVERSE_RECOVER|qty:MONEY|rel:eq(mul(#,#),mul(X,add(#,#)))|path:add>multiply>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'PL_H_SAME_PRICE_PAIR', family: 'profit_loss', band: 'hard', task: 'COMBINE_PARTS/MONEY', info: 'TWO_CONFIGURATIONS', targets: ['netLossOnPair', 'totalCostOfPair'], signatures: ['task:COMBINE_PARTS|qty:MONEY|rel:eq(X,add(#,#))|path:add>percent>multiply>divide>subtract|info:TWO_CONFIGURATIONS|entry:reverse', 'task:COMBINE_PARTS|qty:MONEY|rel:eq(add(#,#),add(X,mul(#,#)))|path:add>percent>multiply>divide>subtract|info:TWO_CONFIGURATIONS|entry:reverse']},
  {templateId: 'PL_H_TWO_OUTCOMES', family: 'profit_loss', band: 'medium', task: 'DECOMPOSE_COMBINED/MONEY', info: 'TWO_CONFIGURATIONS', targets: ['costFromTwoCases'], signatures: ['task:DECOMPOSE_COMBINED|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'PL_M_DISC_MARK', family: 'profit_loss', band: 'medium', task: 'APPLY_SUCCESSIVE_CHANGE/MONEY', info: 'MULTI_STAGE_PROCESS', targets: ['sellPriceAfterDiscountAndMarkup'], signatures: ['task:APPLY_SUCCESSIVE_CHANGE|qty:MONEY|rel:eq(mul(#,X),mul(#,add(#,#),sub(#,#)))|path:multiply>divide>subtract>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'PL_M_TOTAL_COST', family: 'profit_loss', band: 'medium', task: 'MEASURE_CHANGE/PERCENT', info: 'PARTITION_OF_WHOLE', targets: ['profitPercentOnTotalCost'], signatures: ['task:MEASURE_CHANGE|qty:PERCENT|rel:eq(mul(#,sub(#,add(#,#))),mul(X,add(#,#)))|path:add>subtract>multiply>divide|info:PARTITION_OF_WHOLE|entry:forward']},
  {templateId: 'RAT_E_KNOWN', family: 'ratios', band: 'easy', task: 'SHARE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['sideA', 'sideB'], signatures: ['task:SHARE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'RAT_E_SPLIT', family: 'ratios', band: 'easy', task: 'SHARE_PROPORTIONALLY/QUANTITY', info: 'PARTITION_OF_WHOLE', targets: ['sideA', 'sideB'], signatures: ['task:SHARE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'RAT_H_MAX_PART', family: 'ratios', band: 'hard', task: 'FIND_THRESHOLD/QUANTITY', info: 'CONSTRAINT_SET', targets: ['largestSecondShare'], signatures: ['task:FIND_THRESHOLD|qty:QUANTITY|rel:eq(#,mod(X,#)) & eq(mul(#,#),mul(#,X))|path:add>ratio>multiply|info:CONSTRAINT_SET|entry:maximum']},
  {templateId: 'RAT_H_TRANSFER', family: 'ratios', band: 'medium', task: 'REVERSE_RECOVER/QUANTITY', info: 'BEFORE_AFTER_CHANGE', targets: ['sideABeforeTransfer', 'sideBBeforeTransfer'], signatures: ['task:REVERSE_RECOVER|qty:QUANTITY|rel:eq(#,mod(X,#)) & eq(mul(#,#,sub(X,#)),mul(#,add(mul(#,#),mul(#,X))))|path:add>subtract>ratio>multiply>divide|info:BEFORE_AFTER_CHANGE|entry:forward', 'task:REVERSE_RECOVER|qty:QUANTITY|rel:eq(#,mod(X,#)) & eq(mul(#,mul(#,add(#,X))),mul(#,sub(mul(#,X),mul(#,#))))|path:add>subtract>ratio>multiply>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'RAT_H_TWO_COMB', family: 'ratios', band: 'hard', task: 'DECOMPOSE_COMBINED/NUMBER', info: 'CONSTRAINT_SET', targets: ['thirdTerm'], signatures: ['task:DECOMPOSE_COMBINED|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'RAT_M_ADD_SIDE', family: 'ratios', band: 'medium', task: 'REVERSE_RECOVER/QUANTITY', info: 'BEFORE_AFTER_CHANGE', targets: ['sumBeforeChange'], signatures: ['task:REVERSE_RECOVER|qty:QUANTITY|rel:eq(#,mod(mul(#,X),#)) & eq(mul(#,#,#,X),mul(#,#,add(mul(#,#),mul(#,X))))|path:add>ratio>multiply>subtract>divide|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'RAT_M_COMMON_DIFF', family: 'ratios', band: 'hard', task: 'COMBINE_PARTS/QUANTITY', info: 'CONSTRAINT_SET', targets: ['sumOfAllThree'], signatures: ['task:COMBINE_PARTS|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'RAT_M_COMMON_SUM', family: 'ratios', band: 'hard', task: 'DECOMPOSE_COMBINED/NUMBER', info: 'CONSTRAINT_SET', targets: ['commonTerm'], signatures: ['task:DECOMPOSE_COMBINED|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'REL_E_BETWEEN', family: 'relational', band: 'easy', task: 'LOCATE_IN_ORDER/PERSON', info: 'RELATIONAL_STATEMENTS', targets: ['position2', 'position4'], signatures: ['task:LOCATE_IN_ORDER|qty:PERSON|rel:order:small/linear/simple/mid/total|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_E_CHAIN', family: 'relational', band: 'easy', task: 'LOCATE_IN_ORDER/PERSON', info: 'RELATIONAL_STATEMENTS', targets: ['position2', 'position4'], signatures: ['task:LOCATE_IN_ORDER|qty:PERSON|rel:order:small/linear/simple/mid/total|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_H_COUNT_BRANCHED', family: 'relational', band: 'hard', task: 'COUNT_SATISFYING/COUNT', info: 'RELATIONAL_STATEMENTS', targets: ['countAbove'], signatures: ['task:COUNT_SATISFYING|qty:COUNT|rel:order:large/branched/merging/deep/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:large/branched/merging/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/merging/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/merging/shallow/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/branched/merging/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/branched/merging/shallow/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_H_GUARANTEE', family: 'relational', band: 'medium', task: 'JUDGE_ENTAILMENT/STATEMENT', info: 'RELATIONAL_STATEMENTS', targets: ['guaranteedDespiteBranches'], signatures: ['task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/merging/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/simple/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/simple/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/linear/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_H_POSITION', family: 'relational', band: 'hard', task: 'LOCATE_IN_ORDER/PERSON', info: 'RELATIONAL_STATEMENTS', targets: ['position2', 'position3', 'position4', 'position5', 'position6', 'position7', 'position8', 'position9', 'undeterminedPosition2', 'undeterminedPosition3', 'undeterminedPosition6', 'undeterminedPosition7', 'undeterminedPosition8', 'undeterminedPosition9'], signatures: ['task:LOCATE_IN_ORDER|qty:PERSON|rel:order:large/branched/simple/deep/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:LOCATE_IN_ORDER|qty:PERSON|rel:order:large/branched/simple/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:LOCATE_IN_ORDER|qty:PERSON|rel:order:large/linear/merging/deep/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:LOCATE_IN_ORDER|qty:PERSON|rel:order:large/linear/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_M_BRANCH_UNRES', family: 'relational', band: 'hard', task: 'JUDGE_INDETERMINACY/STATEMENT', info: 'RELATIONAL_STATEMENTS', targets: ['undeterminedPair'], signatures: ['task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:mid/branched/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:mid/branched/merging/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:mid/branched/simple/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:mid/branched/simple/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:small/branched/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:small/branched/merging/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:small/branched/simple/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_INDETERMINACY|qty:STATEMENT|rel:order:small/branched/simple/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_M_CHAIN6', family: 'relational', band: 'medium', task: 'LOCATE_IN_ORDER/PERSON', info: 'RELATIONAL_STATEMENTS', targets: ['position2', 'position3', 'position4', 'position5'], signatures: ['task:LOCATE_IN_ORDER|qty:PERSON|rel:order:mid/linear/simple/deep/total|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_M_CONFIRM', family: 'relational', band: 'medium', task: 'JUDGE_ENTAILMENT/STATEMENT', info: 'RELATIONAL_STATEMENTS', targets: ['guaranteedStatement'], signatures: ['task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/merging/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/simple/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:mid/branched/simple/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:small/branched/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:small/branched/merging/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:small/branched/simple/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:small/branched/simple/shallow/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward', 'task:JUDGE_ENTAILMENT|qty:STATEMENT|rel:order:small/linear/merging/mid/partial|path:none|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'REL_M_COUNT', family: 'relational', band: 'medium', task: 'COUNT_SATISFYING/COUNT', info: 'RELATIONAL_STATEMENTS', targets: ['countAbove'], signatures: ['task:COUNT_SATISFYING|qty:COUNT|rel:order:large/branched/merging/deep/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:large/branched/merging/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:large/branched/simple/deep/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:large/branched/simple/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/merging/deep/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/merging/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/merging/shallow/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/simple/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/branched/simple/shallow/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/linear/merging/deep/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:mid/linear/simple/deep/total|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/branched/merging/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/branched/merging/shallow/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/branched/simple/mid/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/branched/simple/shallow/partial|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward', 'task:COUNT_SATISFYING|qty:COUNT|rel:order:small/linear/simple/mid/total|path:ratio|info:RELATIONAL_STATEMENTS|entry:forward']},
  {templateId: 'SEQ_E_ARITH', family: 'sequences', band: 'easy', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_CONSTANT_DIFFERENCE', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>add|info:RUN_CONSTANT_DIFFERENCE|entry:forward']},
  {templateId: 'SEQ_E_ARITH', family: 'sequences', band: 'easy', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_CONSTANT_DIFFERENCE', targets: ['missingMiddleTerm', 'previousTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,X))|path:subtract>ratio|info:RUN_CONSTANT_DIFFERENCE|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,X)) & eq(#,sub(X,#))|path:subtract>ratio>add|info:RUN_CONSTANT_DIFFERENCE|entry:forward']},
  {templateId: 'SEQ_E_GEO', family: 'sequences', band: 'easy', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_CONSTANT_RATIO', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,X))|path:divide>ratio|info:RUN_CONSTANT_RATIO|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(X,mul(#,#))|path:divide>ratio>multiply|info:RUN_CONSTANT_RATIO|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,X))|path:divide>ratio|info:RUN_CONSTANT_RATIO|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(X,mul(#,#))|path:divide>ratio>multiply|info:RUN_CONSTANT_RATIO|entry:forward']},
  {templateId: 'SEQ_E_GEO', family: 'sequences', band: 'easy', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_CONSTANT_RATIO', targets: ['missingMiddleTerm', 'previousTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,X))|path:divide>ratio|info:RUN_CONSTANT_RATIO|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(X,mul(#,#))|path:divide>ratio>multiply|info:RUN_CONSTANT_RATIO|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,X))|path:divide>ratio|info:RUN_CONSTANT_RATIO|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(X,mul(#,#))|path:divide>ratio>multiply|info:RUN_CONSTANT_RATIO|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,X)) & eq(X,mul(#,#))|path:divide>ratio|info:RUN_CONSTANT_RATIO|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,X)) & eq(X,mul(#,#))|path:multiply>ratio|info:RUN_CONSTANT_RATIO|entry:forward']},
  {templateId: 'SEQ_H_ALT_DIV', family: 'sequences', band: 'hard', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_ALTERNATING_OPERATIONS', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,X)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#))|path:divide>subtract>ratio|info:RUN_ALTERNATING_OPERATIONS|entry:forward']},
  {templateId: 'SEQ_H_DIGIT_PRODUCT', family: 'sequences', band: 'hard', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_DIGIT_FUNCTION', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,add(#,#)) & eq(#,add(#,#)) & eq(#,add(#,#)) & eq(#,add(#,#)) & eq(X,add(#,#))|path:subtract>ratio>multiply>add|info:RUN_DIGIT_FUNCTION|entry:forward']},
  {templateId: 'SEQ_H_DIGIT_SUM', family: 'sequences', band: 'hard', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_DIGIT_FUNCTION', targets: ['nextTerm', 'termAfterNext'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:add>ratio|info:RUN_DIGIT_FUNCTION|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:add>ratio|info:RUN_DIGIT_FUNCTION|entry:forward']},
  {templateId: 'SEQ_H_INDEX_MULT', family: 'sequences', band: 'hard', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_POSITION_DEPENDENT', targets: ['nextTerm', 'termAfterNext'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,#) & eq(#,#) & eq(#,#) & eq(#,#) & eq(#,#) & eq(#,X)|path:multiply>add>ratio|info:RUN_POSITION_DEPENDENT|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,#) & eq(#,#) & eq(#,#) & eq(#,#) & eq(#,X)|path:multiply>add>ratio|info:RUN_POSITION_DEPENDENT|entry:forward']},
  {templateId: 'SEQ_H_POW_INDEX', family: 'sequences', band: 'hard', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_POSITION_DEPENDENT', targets: ['nextTerm', 'termAfterNext'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>multiply>add|info:RUN_POSITION_DEPENDENT|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>multiply>add|info:RUN_POSITION_DEPENDENT|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>multiply>add|info:RUN_POSITION_DEPENDENT|entry:forward']},
  {templateId: 'SEQ_H_POW_INDEX', family: 'sequences', band: 'hard', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_POSITION_DEPENDENT', targets: ['previousTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>divide>add|info:RUN_POSITION_DEPENDENT|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>divide>add|info:RUN_POSITION_DEPENDENT|entry:forward']},
  {templateId: 'SEQ_H_RECURRENCE', family: 'sequences', band: 'hard', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_SUM_OF_PREVIOUS', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(X,add(#,mul(#,#)))|path:add>multiply>ratio|info:RUN_SUM_OF_PREVIOUS|entry:forward']},
  {templateId: 'SEQ_H_RECURRENCE', family: 'sequences', band: 'hard', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_SUM_OF_PREVIOUS', targets: ['missingMiddleTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,add(#,mul(#,X))) & eq(X,add(#,mul(#,#)))|path:add>multiply>ratio|info:RUN_SUM_OF_PREVIOUS|entry:forward']},
  {templateId: 'SEQ_M_ALT_OPS', family: 'sequences', band: 'medium', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_ALTERNATING_OPERATIONS', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(X,#))|path:multiply>add>ratio|info:RUN_ALTERNATING_OPERATIONS|entry:forward']},
  {templateId: 'SEQ_M_CANDIDATE', family: 'sequences', band: 'medium', task: 'SELECT_BY_RULE/TERM', info: 'RUN_WITH_MEMBERSHIP_CHOICE', targets: ['sequenceMember'], signatures: ['task:SELECT_BY_RULE|qty:TERM|rel:eq(X,add(#,mul(#,#)))|path:subtract>divide>ratio|info:RUN_WITH_MEMBERSHIP_CHOICE|entry:forward']},
  {templateId: 'SEQ_M_CYCLE3', family: 'sequences', band: 'medium', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_OPERATION_CYCLE', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,add(#,#)) & eq(#,add(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(X,add(#,#))|path:multiply>add>subtract>ratio|info:RUN_OPERATION_CYCLE|entry:forward']},
  {templateId: 'SEQ_M_DOUBLE_DIFF', family: 'sequences', band: 'medium', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_SECOND_DIFFERENCE', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>multiply>add|info:RUN_SECOND_DIFFERENCE|entry:forward']},
  {templateId: 'SEQ_M_DOUBLE_DIFF', family: 'sequences', band: 'medium', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_SECOND_DIFFERENCE', targets: ['missingMiddleTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,X)) & eq(#,sub(X,#))|path:add|info:RUN_SECOND_DIFFERENCE|entry:forward', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,X)) & eq(#,sub(X,#))|path:multiply>add|info:RUN_SECOND_DIFFERENCE|entry:forward']},
  {templateId: 'SEQ_M_INC_DIFF', family: 'sequences', band: 'medium', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_GROWING_DIFFERENCE', targets: ['nextTerm'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio>add|info:RUN_GROWING_DIFFERENCE|entry:forward']},
  {templateId: 'SEQ_M_INC_DIFF', family: 'sequences', band: 'medium', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_GROWING_DIFFERENCE', targets: ['missingMiddleTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,sub(#,X)) & eq(#,sub(X,#))|path:multiply>add|info:RUN_GROWING_DIFFERENCE|entry:forward']},
  {templateId: 'SEQ_M_INTERLEAVED', family: 'sequences', band: 'medium', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_TWO_INTERLEAVED', targets: ['nextTermOfSecondRun'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(X,#))|path:subtract>ratio|info:RUN_TWO_INTERLEAVED|entry:forward']},
  {templateId: 'SEQ_M_LINEAR_RECUR', family: 'sequences', band: 'medium', task: 'CONTINUE_PATTERN/TERM', info: 'RUN_AFFINE_RECURRENCE', targets: ['nextTerm', 'termAfterNext'], signatures: ['task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(X,add(#,mul(#,#)))|path:multiply>add>ratio|info:RUN_AFFINE_RECURRENCE|entry:forward', 'task:CONTINUE_PATTERN|qty:TERM|rel:eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(X,add(#,mul(#,#)))|path:multiply>add>subtract>ratio|info:RUN_AFFINE_RECURRENCE|entry:forward']},
  {templateId: 'SEQ_M_LINEAR_RECUR', family: 'sequences', band: 'medium', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_AFFINE_RECURRENCE', targets: ['previousTerm'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,X)))|path:multiply>add>ratio>divide>subtract|info:RUN_AFFINE_RECURRENCE|entry:reverse', 'task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,#))) & eq(#,add(#,mul(#,X)))|path:multiply>add>subtract>ratio>divide|info:RUN_AFFINE_RECURRENCE|entry:reverse']},
  {templateId: 'SEQ_M_MISSING_OP', family: 'sequences', band: 'medium', task: 'IDENTIFY_RULE/RULE', info: 'RUN_WITH_HIDDEN_OPERATION', targets: ['missingOperation'], signatures: ['task:IDENTIFY_RULE|qty:RULE|rel:eq(#,mul(#,X))|path:subtract>multiply>ratio|info:RUN_WITH_HIDDEN_OPERATION|entry:forward']},
  {templateId: 'SEQ_M_PAIR_RULE', family: 'sequences', band: 'medium', task: 'RECOVER_PATTERN_TERM/TERM', info: 'RUN_WITHIN_PAIR', targets: ['secondOfPair'], signatures: ['task:RECOVER_PATTERN_TERM|qty:TERM|rel:eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,mul(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(#,sub(#,#)) & eq(X,mul(#,#))|path:ratio>subtract>multiply|info:RUN_WITHIN_PAIR|entry:forward']},
  {templateId: 'SEQ_M_RULE_APPLY', family: 'sequences', band: 'medium', task: 'FORWARD_COMPUTE/TERM', info: 'RULE_STATED_IN_WORDS', targets: ['termFromStatedRule'], signatures: ['task:FORWARD_COMPUTE|qty:TERM|rel:eq(#,X)|path:multiply>add|info:RULE_STATED_IN_WORDS|entry:forward']},
  {templateId: 'SEQ_M_RULE_ID', family: 'sequences', band: 'medium', task: 'IDENTIFY_RULE/RULE', info: 'RUN_WITH_RULE_OPTIONS', targets: ['generatingRule'], signatures: ['task:IDENTIFY_RULE|qty:RULE|rel:none|path:subtract>multiply>add>ratio|info:RUN_WITH_RULE_OPTIONS|entry:forward', 'task:IDENTIFY_RULE|qty:RULE|rel:none|path:subtract>multiply>ratio|info:RUN_WITH_RULE_OPTIONS|entry:forward']},
  {templateId: 'SEQ_M_WRONG_TERM', family: 'sequences', band: 'medium', task: 'DETECT_PATTERN_FAULT/TERM', info: 'RUN_CONSTANT_DIFFERENCE', targets: ['wrongTerm'], signatures: ['task:DETECT_PATTERN_FAULT|qty:TERM|rel:eq(#,X) & eq(#,add(#,#))|path:ratio>add|info:RUN_CONSTANT_DIFFERENCE|entry:comparison', 'task:DETECT_PATTERN_FAULT|qty:TERM|rel:eq(#,X) & eq(#,mul(#,#))|path:ratio>multiply|info:RUN_CONSTANT_DIFFERENCE|entry:comparison']},
  {templateId: 'SPD_E_DISTANCE', family: 'speed', band: 'easy', task: 'FORWARD_COMPUTE/DISTANCE', info: 'DIRECT_GIVENS', targets: ['distance'], signatures: ['task:FORWARD_COMPUTE|qty:DISTANCE|rel:eq(X,mul(#,#))|path:multiply|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'SPD_E_TIME', family: 'speed', band: 'easy', task: 'FORWARD_COMPUTE/DURATION', info: 'DIRECT_GIVENS', targets: ['time'], signatures: ['task:FORWARD_COMPUTE|qty:DURATION|rel:eq(#,mul(#,X))|path:divide|info:DIRECT_GIVENS|entry:forward']},
  {templateId: 'SPD_H_CATCH', family: 'speed', band: 'medium', task: 'FIND_COINCIDENCE/DURATION', info: 'TWO_MOVING_BODIES', targets: ['catchupTime'], signatures: ['task:FIND_COINCIDENCE|qty:DURATION|rel:eq(mul(#,X),mul(#,add(#,X)))|path:multiply>subtract>divide|info:TWO_MOVING_BODIES|entry:forward']},
  {templateId: 'SPD_H_CURRENT', family: 'speed', band: 'hard', task: 'DECOMPOSE_COMBINED/SPEED', info: 'CONSTRAINT_SET', targets: ['boatSpeed', 'currentSpeed'], signatures: ['task:DECOMPOSE_COMBINED|qty:SPEED|rel:eq(add(#,#),mul(#,X))|path:divide>add>ratio|info:CONSTRAINT_SET|entry:forward', 'task:DECOMPOSE_COMBINED|qty:SPEED|rel:eq(mul(#,X),sub(#,#))|path:divide>subtract>ratio|info:CONSTRAINT_SET|entry:reverse']},
  {templateId: 'SPD_H_LEG_SPLIT', family: 'speed', band: 'hard', task: 'DECOMPOSE_COMBINED/DISTANCE', info: 'MULTI_STAGE_PROCESS', targets: ['firstLegDistance'], signatures: ['task:DECOMPOSE_COMBINED|qty:DISTANCE|rel:eq(add(mul(#,X),mul(#,sub(#,X))),mul(#,#))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:reverse']},
  {templateId: 'SPD_H_LEG_SPLIT', family: 'speed', band: 'hard', task: 'DECOMPOSE_COMBINED/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['secondLegHours'], signatures: ['task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(#,add(mul(#,X),mul(#,sub(#,X))))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:reverse']},
  {templateId: 'SPD_H_MEET_DELAY', family: 'speed', band: 'medium', task: 'FIND_COINCIDENCE/DURATION', info: 'TWO_MOVING_BODIES', targets: ['meetingTime'], signatures: ['task:FIND_COINCIDENCE|qty:DURATION|rel:eq(#,add(mul(#,X),mul(#,add(#,X))))|path:multiply>subtract>add>divide|info:TWO_MOVING_BODIES|entry:forward']},
  {templateId: 'SPD_H_TIME_DIFF', family: 'speed', band: 'medium', task: 'DECOMPOSE_COMBINED/DISTANCE', info: 'TWO_CONFIGURATIONS', targets: ['distanceFromTimeGap'], signatures: ['task:DECOMPOSE_COMBINED|qty:DISTANCE|rel:eq(mul(#,#,#),mul(X,sub(#,#)))|path:divide>subtract>ratio>multiply|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'SPD_M_AVG', family: 'speed', band: 'medium', task: 'COMBINE_PARTS/SPEED', info: 'MULTI_STAGE_PROCESS', targets: ['averageSpeed'], signatures: ['task:COMBINE_PARTS|qty:SPEED|rel:eq(add(mul(#,#),mul(#,#)),mul(X,add(#,#)))|path:multiply>add>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'SPD_M_EQUAL_DIST', family: 'speed', band: 'medium', task: 'COMBINE_PARTS/DISTANCE', info: 'MULTI_STAGE_PROCESS', targets: ['totalDistance'], signatures: ['task:COMBINE_PARTS|qty:DISTANCE|rel:eq(mul(#,#,#,#),mul(X,add(#,#)))|path:divide>multiply>add>ratio|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'SPD_M_TWO_TIME', family: 'speed', band: 'medium', task: 'COMBINE_PARTS/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['totalTimeMinutes'], signatures: ['task:COMBINE_PARTS|qty:DURATION|rel:eq(mul(#,#,X),mul(#,add(mul(#,#),mul(#,#))))|path:divide>add>multiply|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'RATE_E_DIRECT', family: 'unit_rate', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'RATE_E_TIME', family: 'unit_rate', band: 'easy', task: 'REQUIRED_INPUT/DURATION', info: 'DIRECT_GIVENS', targets: ['requiredTime'], signatures: ['task:REQUIRED_INPUT|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'RATE_H_RATE_FROM_GAP', family: 'unit_rate', band: 'hard', task: 'DECOMPOSE_COMBINED/RATE', info: 'TWO_CONFIGURATIONS', targets: ['increasedRate'], signatures: ['task:DECOMPOSE_COMBINED|qty:RATE|rel:eq(mul(#,#),mul(#,X,sub(X,#)))|path:divide>add>multiply>ratio|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'RATE_H_RATE_FROM_GAP', family: 'unit_rate', band: 'hard', task: 'REVERSE_RECOVER/RATE', info: 'TWO_CONFIGURATIONS', targets: ['originalRate'], signatures: ['task:REVERSE_RECOVER|qty:RATE|rel:eq(mul(#,#),mul(#,X,add(#,X)))|path:divide>add>multiply>ratio|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'RATE_H_TARGET', family: 'unit_rate', band: 'medium', task: 'REQUIRED_INPUT/DURATION', info: 'BEFORE_AFTER_CHANGE', targets: ['requiredTimeAfterIncrease'], signatures: ['task:REQUIRED_INPUT|qty:DURATION|rel:eq(mul(#,#,#),mul(#,X,add(#,#)))|path:divide>add>multiply|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'RATE_H_TWO_PHASE', family: 'unit_rate', band: 'medium', task: 'COMBINE_PARTS/QUANTITY', info: 'MULTI_STAGE_PROCESS', targets: ['totalAcrossStages'], signatures: ['task:COMBINE_PARTS|qty:QUANTITY|rel:eq(add(mul(#,#,#),mul(#,#,add(#,#))),mul(#,X))|path:multiply>divide>add|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'RATE_M_PERCENT', family: 'unit_rate', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'BEFORE_AFTER_CHANGE', targets: ['scaledOutputAfterIncrease'], signatures: ['task:SCALE_PROPORTIONALLY|qty:QUANTITY|rel:eq(mul(#,#,X),mul(#,#,add(#,#)))|path:divide>add>multiply|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'RATE_M_SCALE', family: 'unit_rate', band: 'easy', task: 'SCALE_PROPORTIONALLY/QUANTITY', info: 'DIRECT_GIVENS', targets: ['scaledOutput'], signatures: ['task:SCALE_PROPORTIONALLY|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'WORK_E_INVERSE', family: 'work_time', band: 'easy', task: 'FORWARD_COMPUTE/DURATION', info: 'DIRECT_GIVENS', targets: ['daysForNewCrew'], signatures: ['task:FORWARD_COMPUTE|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'WORK_E_VOLUME', family: 'work_time', band: 'easy', task: 'REQUIRED_INPUT/COUNT', info: 'DIRECT_GIVENS', targets: ['workersForMoreWork'], signatures: ['task:REQUIRED_INPUT|arch:FOURTH_PROPORTION|entry:forward']},
  {templateId: 'WORK_H_EXTRA_WORKERS', family: 'work_time', band: 'medium', task: 'REQUIRED_INPUT/COUNT', info: 'MULTI_STAGE_PROCESS', targets: ['extraWorkers'], signatures: ['task:REQUIRED_INPUT|qty:COUNT|rel:eq(mul(#,#),mul(add(#,X),sub(#,#)))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'WORK_H_JOINT_SOLO', family: 'work_time', band: 'medium', task: 'DECOMPOSE_COMBINED/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['secondSoloDays'], signatures: ['task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(mul(#,#),mul(X,sub(#,#)))|path:divide>ratio>multiply>subtract|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'WORK_H_SOLO_GAP', family: 'work_time', band: 'hard', task: 'DECOMPOSE_COMBINED/DURATION', info: 'CONSTRAINT_SET', targets: ['fasterSoloDays'], signatures: ['task:DECOMPOSE_COMBINED|qty:DURATION|rel:eq(mul(#,add(#,mul(#,X))),mul(X,add(#,X)))|path:add>divide>ratio>multiply|info:CONSTRAINT_SET|entry:reverse']},
  {templateId: 'WORK_H_THREE_PAIRS', family: 'work_time', band: 'hard', task: 'COMBINE_PARTS/DURATION', info: 'CONSTRAINT_SET', targets: ['threeTogetherDays'], signatures: ['task:COMBINE_PARTS|qty:DURATION|rel:eq(mul(#,mul(#,mul(#,#))),mul(X,add(add(mul(#,#),mul(#,#)),mul(#,#))))|path:divide>ratio>multiply>add|info:CONSTRAINT_SET|entry:forward']},
  {templateId: 'WORK_H_TWO_STAGE', family: 'work_time', band: 'medium', task: 'COMPARE_ALTERNATIVES/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['extraDaysAfterTwoStages'], signatures: ['task:COMPARE_ALTERNATIVES|qty:DURATION|rel:eq(add(mul(#,#),mul(#,#),mul(#,X)),mul(#,#))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'WORK_H_WORKERS_EFF', family: 'work_time', band: 'medium', task: 'COMPARE_ALTERNATIVES/DURATION', info: 'TWO_CONFIGURATIONS', targets: ['extraDaysAfterCrewAndEfficiency'], signatures: ['task:COMPARE_ALTERNATIVES|qty:DURATION|rel:eq(add(mul(#,#,#),mul(#,X,add(#,#))),mul(#,#,#))|path:multiply>subtract>divide>add|info:TWO_CONFIGURATIONS|entry:forward']},
  {templateId: 'WORK_M_CHANGE', family: 'work_time', band: 'medium', task: 'COMPARE_ALTERNATIVES/DURATION', info: 'MULTI_STAGE_PROCESS', targets: ['extraDaysAfterCrewChange'], signatures: ['task:COMPARE_ALTERNATIVES|qty:DURATION|rel:eq(add(mul(#,#),mul(#,X)),mul(#,#))|path:multiply>subtract>add>divide|info:MULTI_STAGE_PROCESS|entry:forward', 'task:COMPARE_ALTERNATIVES|qty:DURATION|rel:eq(add(mul(#,#),mul(#,X)),mul(#,#))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']},
  {templateId: 'WORK_M_EFF', family: 'work_time', band: 'easy', task: 'FORWARD_COMPUTE/DURATION', info: 'BEFORE_AFTER_CHANGE', targets: ['daysAfterEfficiencyGain'], signatures: ['task:FORWARD_COMPUTE|qty:DURATION|rel:eq(mul(#,#),mul(X,add(#,#)))|path:divide>add|info:BEFORE_AFTER_CHANGE|entry:forward']},
  {templateId: 'WORK_M_TARGET', family: 'work_time', band: 'medium', task: 'REQUIRED_INPUT/COUNT', info: 'MULTI_STAGE_PROCESS', targets: ['workersForDeadline'], signatures: ['task:REQUIRED_INPUT|qty:COUNT|rel:eq(add(mul(#,#),mul(#,X)),mul(#,#))|path:multiply>subtract>divide|info:MULTI_STAGE_PROCESS|entry:forward']}
].map(Object.freeze));

/** A blueprint's identity for scheduling: the idea, not the instance. */
export const blueprintId = b => `${b.family}|${b.templateId}|${b.task}`;

/** Same family, same job, same layout — the unit a reader perceives as "again". */
export const presentationOf = b => `${b.family}|${b.task}|${b.info}`;

const byKey = new Map();
for (const b of BLUEPRINTS) byKey.set(`${b.templateId}|${b.task}`, b);

/**
 * The blueprint a finished question realises. A template that gains a task the
 * catalogue has not recorded yet still gets a blueprint here rather than a null,
 * so the scheduler's accounting stays complete; the catalogue test is what makes
 * that case visible instead of permanent.
 */
export function blueprintFor(templateId, task, family = '?', band = '?', info = 'DIRECT_GIVENS') {
  return byKey.get(`${templateId}|${task}`)
    ?? {templateId, family, band, task, info, targets: [], uncatalogued: true};
}

const byBand = new Map();
for (const b of BLUEPRINTS) {
  if (!byBand.has(b.band)) byBand.set(b.band, []);
  byBand.get(b.band).push(b);
}

/** Every blueprint that can fill a slot of this band, optionally within a family pool. */
export function blueprintsForBand(band, families = null) {
  const all = byBand.get(band) ?? [];
  if (!families || !families.length) return all;
  const allowed = new Set(families);
  return all.filter(b => allowed.has(b.family));
}

/** How much genuinely distinct material a band holds. Reported, never adjusted. */
export function bandCapacity(band, families = null) {
  const pool = blueprintsForBand(band, families);
  return {
    band,
    blueprints: pool.length,
    families: new Set(pool.map(b => b.family)).size,
    tasks: new Set(pool.map(b => b.task)).size,
    presentations: new Set(pool.map(presentationOf)).size
  };
}
